version: '3'

services:
  omada:
    build:
      context: .
      args:
        YEAR: "2022"
        MONTH: "01"
        DAY: "20"
        VERSION: "5.0.30"
    container_name: omada
    image: tarfeef101/omada_controller:5.0.30
    stop_grace_period: 30s
    ports:
      - '8088:8088' 
      - '8043:8043'
      - '8843:8843'
      - '29810-29813:29810-29813'
      - '29810-29813:29810-29813/udp'
    volumes:
      - './data:/opt/tplink/EAPController/data'
